export const mockDB = [
  {
    data: [
      {
        _id: 1,
        userId: 101,
        user: "Alice",
        title: "Post 1",
        description: "Description of post 1",
        likes: 3,
        likedUsers: [102, 103],
      },
      {
        _id: 2,
        userId: 102,
        user: "Bob",
        title: "Post 2",
        description: "Description of post 2",
        likes: 1,
        likedUsers: [101],
      },
      {
        _id: 3,
        userId: 103,
        user: "Charlie",
        title: "Post 3",
        description: "Description of post 3",
        likes: 5,
        likedUsers: [101, 102],
      },
      {
        _id: 4,
        userId: 104,
        user: "David",
        title: "Post 4",
        description: "Description of post 4",
        likes: 0,
        likedUsers: [],
      },
      {
        _id: 5,
        userId: 105,
        user: "Eve",
        title: "Post 5",
        description: "Description of post 5",
        likes: 2,
        likedUsers: [101],
      },
    ],
    nextCursor: 6,
  },

  {
    data: [
      {
        _id: 6,
        userId: 101,
        user: "Alice",
        title: "Post 6",
        description: "Description of post 6",
        likes: 7,
        likedUsers: [102],
      },
      {
        _id: 7,
        userId: 102,
        user: "Bob",
        title: "Post 7",
        description: "Description of post 7",
        likes: 4,
        likedUsers: [103],
      },
      {
        _id: 8,
        userId: 103,
        user: "Charlie",
        title: "Post 8",
        description: "Description of post 8",
        likes: 9,
        likedUsers: [101, 104],
      },
      {
        _id: 9,
        userId: 104,
        user: "David",
        title: "Post 9",
        description: "Description of post 9",
        likes: 2,
        likedUsers: [],
      },
      {
        _id: 10,
        userId: 105,
        user: "Eve",
        title: "Post 10",
        description: "Description of post 10",
        likes: 6,
        likedUsers: [102],
      },
    ],
    nextCursor: 11,
  },

  {
    data: [
      {
        _id: 11,
        userId: 101,
        user: "Alice",
        title: "Post 11",
        description: "Description of post 11",
        likes: 3,
        likedUsers: [],
      },
      {
        _id: 12,
        userId: 102,
        user: "Bob",
        title: "Post 12",
        description: "Description of post 12",
        likes: 8,
        likedUsers: [103],
      },
      {
        _id: 13,
        userId: 103,
        user: "Charlie",
        title: "Post 13",
        description: "Description of post 13",
        likes: 1,
        likedUsers: [101],
      },
      {
        _id: 14,
        userId: 104,
        user: "David",
        title: "Post 14",
        description: "Description of post 14",
        likes: 10,
        likedUsers: [105],
      },
      {
        _id: 15,
        userId: 105,
        user: "Eve",
        title: "Post 15",
        description: "Description of post 15",
        likes: 4,
        likedUsers: [101, 102],
      },
    ],
    nextCursor: 16,
  },

  {
    data: [
      {
        _id: 16,
        userId: 101,
        user: "Alice",
        title: "Post 16",
        description: "Description of post 16",
        likes: 6,
        likedUsers: [],
      },
      {
        _id: 17,
        userId: 102,
        user: "Bob",
        title: "Post 17",
        description: "Description of post 17",
        likes: 2,
        likedUsers: [103],
      },
      {
        _id: 18,
        userId: 103,
        user: "Charlie",
        title: "Post 18",
        description: "Description of post 18",
        likes: 7,
        likedUsers: [104],
      },
      {
        _id: 19,
        userId: 104,
        user: "David",
        title: "Post 19",
        description: "Description of post 19",
        likes: 5,
        likedUsers: [101],
      },
      {
        _id: 20,
        userId: 105,
        user: "Eve",
        title: "Post 20",
        description: "Description of post 20",
        likes: 9,
        likedUsers: [102, 103],
      },
    ],
    nextCursor: 21,
  },

  {
    data: [
      {
        _id: 21,
        userId: 101,
        user: "Alice",
        title: "Post 21",
        description: "Description of post 21",
        likes: 1,
        likedUsers: [],
      },
      {
        _id: 22,
        userId: 102,
        user: "Bob",
        title: "Post 22",
        description: "Description of post 22",
        likes: 3,
        likedUsers: [101],
      },
      {
        _id: 23,
        userId: 103,
        user: "Charlie",
        title: "Post 23",
        description: "Description of post 23",
        likes: 11,
        likedUsers: [104, 105],
      },
      {
        _id: 24,
        userId: 104,
        user: "David",
        title: "Post 24",
        description: "Description of post 24",
        likes: 8,
        likedUsers: [101],
      },
      {
        _id: 25,
        userId: 105,
        user: "Eve",
        title: "Post 25",
        description: "Description of post 25",
        likes: 6,
        likedUsers: [102, 103],
      },
    ],
    nextCursor: null,
  },
];
